In [2]:
import pandas as pd

data = pd.read_csv('dataset/coin_Bitcoin.csv', date_parser = True)

In [3]:
data.tail()

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
2986,2987,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,2988,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,2989,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,2990,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,2991,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [6]:
data_training = data[data['Date']< '2021-01-01'].copy()
data_training

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
...,...,...,...,...,...,...,...,...,...,...
2799,2800,Bitcoin,BTC,2020-12-27 23:59:59,28288.840022,25922.769765,26439.373289,26272.294567,6.647990e+10,4.882133e+11
2800,2801,Bitcoin,BTC,2020-12-28 23:59:59,27389.112064,26207.639931,26280.821415,27084.807886,4.905674e+10,5.033393e+11
2801,2802,Bitcoin,BTC,2020-12-29 23:59:59,27370.720084,25987.298075,27081.809729,27362.436557,4.526595e+10,5.085237e+11
2802,2803,Bitcoin,BTC,2020-12-30 23:59:59,28937.740004,27360.089709,27360.089709,28840.953420,5.128744e+10,5.360338e+11
2803,2804,Bitcoin,BTC,2020-12-31 23:59:59,29244.876688,28201.991994,28841.573758,29001.719822,4.675496e+10,5.390511e+11

In [7]:
data_test = data[data['Date']> '2021-01-01'].copy()
data_test

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
2804,2805,Bitcoin,BTC,2021-01-01 23:59:59,29600.626950,28803.585014,28994.008916,29374.151889,4.073030e+10,5.460016e+11
2805,2806,Bitcoin,BTC,2021-01-02 23:59:59,33155.118819,29091.181191,29376.455834,32127.267939,6.786542e+10,5.972059e+11
2806,2807,Bitcoin,BTC,2021-01-03 23:59:59,34608.556738,32052.317076,32129.407356,32782.024466,7.866524e+10,6.094092e+11
2807,2808,Bitcoin,BTC,2021-01-04 23:59:59,33440.218569,28722.755271,32810.947644,31971.913522,8.116348e+10,5.943840e+11
2808,2809,Bitcoin,BTC,2021-01-05 23:59:59,34437.590592,30221.186739,31977.041132,33992.429344,6.754732e+10,6.319800e+11
...,...,...,...,...,...,...,...,...,...,...
2986,2987,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,2988,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,2989,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,2990,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,2991,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11